---
- name: Install and configure Apache web server
  hosts: all
  become: true
  tasks:

    - name: Install the apache2 package
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure the Apache service is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
