---
- name: Install and configure Apache web server
  hosts: all
  become: true
  tasks:

    - name: Install the apache2 package
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Install PHP and required Apache modules
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Ensure the Apache service is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
