---
- name: Install htop package
  hosts: all
  become: true
  tasks:
    - name: Ensure htop is installed
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: yes
