---
- name: Fully remove Apache and its modules
  hosts: all
  become: true
  tasks:

    - name: Stop and disable the Apache service
      ansible.builtin.service:
        name: apache2
        state: stopped
        enabled: no

    - name: Remove Apache and related PHP packages
      ansible.builtin.apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: absent
        purge: yes
        autoremove: yes
